### ISSUE TITLE
Files are downloaded incompletely for CentOS 7

### ISSUE THREAD

**Issue by stdevel** [stdevel/mkelfs#13]
Kickstarting CentOS 7 fails with the following error:

```Warning: Downloading 'http://spacewalk-hostname/ks/dist/centos-7-x86_64/LiveOS/squashfs.img' failed!```

**Comment by Q-Storm** [comment]
I figured out when you also use the minor Release number as 7.2.1511 the script is not downloading LiveOS folder.
