### ISSUE TITLE
Parameter for ignoring API support

### ISSUE THREAD

**Issue by stdevel** [stdevel/mkelfs#17]
Currently, I need to alter the toolkit after every new release of Spacewalk. It would useful to have a parameter to ignore API level validation as I might not find much time for maintaining this toolkit, anymore. :)

**Comment by Q-Storm** [comment]
Are you sill working on this issue ? Or do you need a PR for a fix, I could create one since I have to fix the api-version with every update.

**Comment by stdevel** [comment]
Hey Q-Storm!
Sorry, found no time so far. So if you want to contribute - I'm happy to check your PR.

Best regards!

**Comment by stdevel** [comment]
Thanks a lot for your contribution!

Fixed in commit 25605e22411efbfb5867bb0e0cd1fde2edb5bca2.
